<p>
    <a href="<?php echo $this->baseUrl("backoffice/data/updateapotheken"); ?>" class="btn btn-primary">Update Apotheken</a> Laatste update: <?php echo $this->apotheek; ?>
</p>
<p>
    <a href="<?php echo $this->baseUrl("backoffice/data/updatehuisartsen"); ?>" class="btn btn-primary">Update Huisartsen</a> Laatste update: <?php echo $this->huisarts; ?>
</p>
<p>
    <a href="<?php echo $this->baseUrl("backoffice/data/updateziekenhuizen"); ?>" class="btn btn-primary">Update Ziekenhuizen</a> Laatste update: <?php echo $this->ziekenhuis; ?>
</p>
<p>
    <a href="<?php echo $this->baseUrl("backoffice/data/updatedierenartsen"); ?>" class="btn btn-primary">Update Dierenartsen</a> Laatste update: <?php echo $this->dierenarts; ?>
</p>
<p>
    <a href="<?php echo $this->baseUrl("backoffice/data/updatehuisartsenwachtposten"); ?>" class="btn btn-primary">Update Huisartsenwachtposten</a> Laatste update: <?php echo $this->huisartsenwachtpost; ?>
</p>