<div class="row">
    <div class="span7">
        <h3>Contact</h3>
        <?php echo $this->form; ?>
    </div>
    <div class="span5">
        <h3>Info</h3>
        <p>Hulp in gent is de eindopdracht van Jannick Vandaele voor het vak New Media Design & Development III aan de Artevelde Hogeschool Gent.</p>
        <p>Alle data die gebruikt wordt in deze website is afkomstig van "The Datatank" en meerbepaald de API van "Apps for Ghent".</p>
        <p>Graag bedank ik mijn lectoren: <br />
        Olivier	Parent <br />       
        Philippe De Pauw – Waterschoot</p>
        <p>&nbsp;</p>
        <p>
            <i class="icon-envelope icon-white"></i> jannvand2@student.arteveldehs.be
        </p>
    </div>
</div>